name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying to GitHub Pages
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: '12'

        - name: Setup git config
          run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"

        - name: Install packages
          run: |
            npm install

        - name: Compute app version
          run: |
            GIT_COUNT=`git rev-list --count main`
            GIT_HASH=`git rev-parse --short main`
            APP_VERSION=$GIT_COUNT.$GIT_HASH
            echo "VUE_APP_VERSION=$APP_VERSION" > .env.production

        - name: Deploy
          run: |
            git checkout --orphan gh-pages
            npm run build
            git --work-tree dist add --all
            git --work-tree dist commit -m "Automated dist build"
            git push origin HEAD:gh-pages --force
